import type {Metadata} from 'next';
import {Inter} from 'next/font/google';
import {ReactNode} from 'react';
import Link from 'next/link';
import './globals.css';

const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

type Props = {
  children: ReactNode;
};

export default function RootLayout({children}: Props) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="flex gap-4 bg-slate-100 p-4">
          <Link href="/">Home</Link>
          <Link href="/test">Test</Link>
        </nav>
        <main className="p-4">{children}</main>
      </body>
    </html>
  );
}
